/**
 * Development/demo seed data. Only runs when SEED_DEMO_DATA=true, so it can
 * never accidentally wipe a real household's data.
 *
 * History is generated by actually driving the app's own services
 * (createTask / recordCompletion) forward in simulated time, rather than
 * hand-computing due dates — that way the seeded data is exactly as
 * internally consistent as data produced by real usage, for both recurrence
 * models.
 */
import { PrismaClient } from "@prisma/client";
import { addDays, calendarDateToUtcDate, utcDateToCalendarDate, type CalendarDate } from "../src/lib/dates";
import { createTask } from "../src/lib/services/task-service";
import { recordCompletion } from "../src/lib/services/completion-service";
import { updateHouseholdSettings } from "../src/lib/services/settings-service";
import type { RecurrenceRule } from "../src/lib/recurrence";

const prisma = new PrismaClient();

function daysAgo(n: number): CalendarDate {
  const now = new Date();
  return addDays({ year: now.getFullYear(), month: now.getMonth() + 1, day: now.getDate() }, -n);
}

function randomInt(min: number, max: number): number {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

function pick<T>(items: T[]): T {
  const item = items[Math.floor(Math.random() * items.length)];
  if (item === undefined) throw new Error("pick() called with an empty array");
  return item;
}

const NOTES = ["took longer than usual", "needed extra supplies", "quick one today", "done before breakfast", null, null, null, null];

interface TaskSeed {
  name: string;
  icon: string;
  areaName: string;
  rule: RecurrenceRule;
  historyStartDaysAgo: number;
  /** Stop simulating once a completion would land within this many days of "now" — controls final due-date state for variety. */
  stopWithinDaysOfNow: number;
  priority?: "LOW" | "MEDIUM" | "HIGH";
  estimatedDurationMinutes?: number;
}

async function main() {
  if (process.env.SEED_DEMO_DATA !== "true") {
    console.log("SEED_DEMO_DATA is not 'true' — skipping demo seed (this is expected in production).");
    return;
  }

  const existingHousehold = await prisma.household.findUnique({ where: { id: 1 } });
  if (existingHousehold?.setupCompleted) {
    console.log("Household is already set up — skipping demo seed to avoid clobbering real data.");
    return;
  }

  console.log("Seeding demo household...");

  await updateHouseholdSettings({
    name: "The Demo Household",
    timezone: "Europe/London",
    setupCompleted: true,
  });

  const [doug, sarah] = await Promise.all([
    prisma.member.create({ data: { name: "Doug", icon: "🧔", order: 0 } }),
    prisma.member.create({ data: { name: "Sarah", icon: "👩", order: 1 } }),
  ]);
  const members = [doug, sarah];

  const areaDefs = [
    { name: "Kitchen", icon: "🍳" },
    { name: "Bathroom", icon: "🛁" },
    { name: "Bedroom", icon: "🛏️" },
    { name: "Living Room", icon: "🛋️" },
    { name: "Garden", icon: "🌿" },
    { name: "Car", icon: "🚗" },
    { name: "General", icon: "🏠" },
  ];
  const areas: Record<string, { id: string }> = {};
  for (let i = 0; i < areaDefs.length; i++) {
    const def = areaDefs[i]!;
    areas[def.name] = await prisma.area.create({ data: { name: def.name, icon: def.icon, order: i } });
  }

  const thursday = { year: 2026, month: 9, day: 24 }; // any real Thursday works as an anchor
  const wednesday = { year: 2026, month: 9, day: 23 };
  const sunday = { year: 2026, month: 9, day: 27 };

  const taskDefs: TaskSeed[] = [
    {
      name: "Hoover downstairs",
      icon: "🧹",
      areaName: "Living Room",
      rule: { type: "COMPLETION_RELATIVE", intervalValue: 7, intervalUnit: "days" },
      historyStartDaysAgo: 200,
      stopWithinDaysOfNow: 1,
    },
    {
      name: "Clean bathroom",
      icon: "🧽",
      areaName: "Bathroom",
      rule: { type: "COMPLETION_RELATIVE", intervalValue: 7, intervalUnit: "days" },
      historyStartDaysAgo: 180,
      stopWithinDaysOfNow: 0,
    },
    {
      name: "Change bedding",
      icon: "🛏️",
      areaName: "Bedroom",
      rule: { type: "COMPLETION_RELATIVE", intervalValue: 14, intervalUnit: "days" },
      historyStartDaysAgo: 180,
      stopWithinDaysOfNow: 2,
    },
    {
      name: "Clean oven",
      icon: "🔥",
      areaName: "Kitchen",
      rule: { type: "COMPLETION_RELATIVE", intervalValue: 60, intervalUnit: "days" },
      historyStartDaysAgo: 240,
      stopWithinDaysOfNow: 5,
      priority: "LOW",
    },
    {
      name: "Descale kettle",
      icon: "🫖",
      areaName: "Kitchen",
      rule: { type: "COMPLETION_RELATIVE", intervalValue: 60, intervalUnit: "days" },
      historyStartDaysAgo: 200,
      stopWithinDaysOfNow: 3,
      priority: "LOW",
    },
    {
      name: "Clean dishwasher filter",
      icon: "🍽️",
      areaName: "Kitchen",
      rule: { type: "COMPLETION_RELATIVE", intervalValue: 30, intervalUnit: "days" },
      historyStartDaysAgo: 180,
      stopWithinDaysOfNow: 1,
    },
    {
      name: "Test smoke alarms",
      icon: "🧯",
      areaName: "General",
      rule: { type: "COMPLETION_RELATIVE", intervalValue: 90, intervalUnit: "days" },
      historyStartDaysAgo: 200,
      stopWithinDaysOfNow: 10,
      priority: "HIGH",
    },
    {
      name: "Vacuum the car",
      icon: "🚗",
      areaName: "Car",
      rule: { type: "COMPLETION_RELATIVE", intervalValue: 30, intervalUnit: "days" },
      historyStartDaysAgo: 150,
      stopWithinDaysOfNow: 4,
    },
    {
      name: "Wipe kitchen surfaces",
      icon: "🧴",
      areaName: "Kitchen",
      rule: { type: "COMPLETION_RELATIVE", intervalValue: 1, intervalUnit: "days" },
      historyStartDaysAgo: 30,
      stopWithinDaysOfNow: 0,
    },
    {
      name: "Put bins out",
      icon: "🗑️",
      areaName: "General",
      rule: {
        type: "FIXED_CALENDAR",
        pattern: { pattern: "weekly", weekdays: [4], intervalWeeks: 1, anchorDate: thursday },
      },
      historyStartDaysAgo: 180,
      stopWithinDaysOfNow: 1,
    },
    {
      name: "Water plants",
      icon: "🪴",
      areaName: "Garden",
      rule: {
        type: "FIXED_CALENDAR",
        pattern: { pattern: "weekly", weekdays: [0], intervalWeeks: 1, anchorDate: sunday },
      },
      historyStartDaysAgo: 120,
      stopWithinDaysOfNow: 2,
    },
    {
      name: "Recycling",
      icon: "♻️",
      areaName: "General",
      rule: {
        type: "FIXED_CALENDAR",
        pattern: { pattern: "weekly", weekdays: [3], intervalWeeks: 2, anchorDate: wednesday },
      },
      historyStartDaysAgo: 180,
      stopWithinDaysOfNow: 3,
    },
    {
      name: "Boiler service",
      icon: "🔧",
      areaName: "General",
      rule: { type: "FIXED_CALENDAR", pattern: { pattern: "annual", month: 10, day: 15 } },
      historyStartDaysAgo: 400,
      stopWithinDaysOfNow: 0,
      priority: "HIGH",
    },
    {
      name: "Deep clean fridge",
      icon: "🧊",
      areaName: "Kitchen",
      rule: { type: "COMPLETION_RELATIVE", intervalValue: 45, intervalUnit: "days" },
      historyStartDaysAgo: 0,
      stopWithinDaysOfNow: 0,
    },
  ];

  for (const def of taskDefs) {
    const startDate = daysAgo(def.historyStartDaysAgo);
    let task = await createTask({
      name: def.name,
      areaId: areas[def.areaName]!.id,
      recurrenceRule: def.rule,
      startDate: def.historyStartDaysAgo > 0 ? startDate : undefined,
      icon: def.icon,
      priority: def.priority ?? "MEDIUM",
      estimatedDurationMinutes: def.estimatedDurationMinutes,
      defaultAssigneeId: null,
    });

    if (def.historyStartDaysAgo === 0) continue; // "Deep clean fridge" is deliberately left with no history

    const now = new Date();
    for (let i = 0; i < 40; i++) {
      const dueCalendarDate = utcDateToCalendarDate(task.dueDate);
      const lateBy = Math.random() < 0.75 ? randomInt(-1, 2) : randomInt(3, 9);
      const completedOn = addDays(dueCalendarDate, lateBy);
      const completedAt = calendarDateToUtcDate(completedOn);
      completedAt.setUTCHours(randomInt(7, 20), randomInt(0, 59));

      if (completedAt.getTime() > now.getTime() - def.stopWithinDaysOfNow * 86_400_000) break;

      const member = pick(members);
      const note = pick(NOTES);
      const result = await recordCompletion({
        taskId: task.id,
        memberId: member.id,
        completedAt,
        note: note ?? undefined,
      });
      task = result.task as typeof task;
    }
  }

  console.log(`Seeded ${taskDefs.length} tasks with realistic history for Doug and Sarah.`);
}

main()
  .catch((err) => {
    console.error(err);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
