# One-time setup of the hosted (multi-household) Choresome on a Windows box,
# alongside -- and fully separate from -- the LAN household instance in
# C:\Apps\choresome (port 3010). Run as an administrator from the hosted
# checkout:
#
#   powershell -ExecutionPolicy Bypass -File scripts\server\hosted\setup-hosted.ps1
#
# Idempotent: safe to re-run. It:
#   1. installs PostgreSQL 17 (winget) if missing, listening on localhost only,
#   2. creates the `choresome` role + database with a random password,
#   3. writes .env.hosted (gitignored) if it doesn't exist yet,
#   4. registers the "Choresome Hosted" startup task.
#
# Deliberately NOT done: opening port 3011 in Windows Firewall. Public traffic
# arrives through a Cloudflare Tunnel (outbound from this machine), so the app
# only needs to be reachable from localhost -- which is also what makes
# TRUST_PROXY=true safe.

param(
    [string]$AppDirectory = "C:\Apps\hosted-choresome",
    [int]$Port = 3011,
    [string]$TaskName = "Choresome Hosted"
)

$ErrorActionPreference = "Stop"
$PgRoot = "C:\Program Files\PostgreSQL\17"
$PgBin = Join-Path $PgRoot "bin"
$PgServiceName = "postgresql-x64-17"
$SecretsFile = Join-Path $AppDirectory ".env.postgres"
$EnvFile = Join-Path $AppDirectory ".env.hosted"

function New-Secret {
    $bytes = New-Object byte[] 24
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
    return [Convert]::ToBase64String($bytes).Replace("+", "-").Replace("/", "_").TrimEnd("=")
}

# Only this account, SYSTEM and Administrators can read files holding secrets.
function Protect-File([string]$Path) {
    $acl = New-Object System.Security.AccessControl.FileSecurity
    $acl.SetAccessRuleProtection($true, $false)
    # SIDs rather than names: account names don't always resolve (e.g. in an SSH session).
    $identities = @(
        [System.Security.Principal.WindowsIdentity]::GetCurrent().User,
        (New-Object System.Security.Principal.SecurityIdentifier("S-1-5-18")),     # SYSTEM
        (New-Object System.Security.Principal.SecurityIdentifier("S-1-5-32-544"))  # Administrators
    )
    foreach ($identity in $identities) {
        $rule = New-Object System.Security.AccessControl.FileSystemAccessRule($identity, "FullControl", "Allow")
        $acl.AddAccessRule($rule)
    }
    Set-Acl -Path $Path -AclObject $acl
}

function Read-EnvValue([string]$Path, [string]$Key) {
    $line = Get-Content $Path | Where-Object { $_ -match "^$Key=" } | Select-Object -First 1
    if (-not $line) { return $null }
    return ($line -replace "^$Key=", "").Trim('"')
}

Write-Host "Setting up hosted Choresome in $AppDirectory (port $Port)..." -ForegroundColor Cyan

# -----------------------------
# 1. PostgreSQL
# -----------------------------

if (-not (Test-Path $SecretsFile)) {
    @(
        "# Local PostgreSQL credentials for hosted Choresome. Generated by setup-hosted.ps1; keep private.",
        "PG_SUPERUSER_PASSWORD=`"$(New-Secret)`"",
        "PG_APP_PASSWORD=`"$(New-Secret)`""
    ) | Set-Content -Path $SecretsFile -Encoding ascii
    Write-Host "Generated database passwords in $SecretsFile."
}
Protect-File $SecretsFile
$SuperPassword = Read-EnvValue $SecretsFile "PG_SUPERUSER_PASSWORD"
$AppPassword = Read-EnvValue $SecretsFile "PG_APP_PASSWORD"

if (-not (Test-Path (Join-Path $PgBin "postgres.exe"))) {
    Write-Host "Installing PostgreSQL 17 (this takes a few minutes)..."
    $override = "--mode unattended --unattendedmodeui none --superpassword $SuperPassword --serverport 5432 " +
        "--enable-components server,commandlinetools --disable-components pgAdmin,stackbuilder"
    winget install -e --id PostgreSQL.PostgreSQL.17 --accept-source-agreements --accept-package-agreements --silent --override $override
    if (-not (Test-Path (Join-Path $PgBin "postgres.exe"))) { throw "PostgreSQL install failed." }
} else {
    Write-Host "PostgreSQL 17 already installed."
}

# Localhost only: nothing on the network (or the internet) can reach the database.
$PgConf = Join-Path $PgRoot "data\postgresql.conf"
$conf = Get-Content $PgConf
if (-not ($conf -match "^listen_addresses = 'localhost'")) {
    $conf = $conf | Where-Object { $_ -notmatch "^\s*listen_addresses\s*=" }
    $conf += "listen_addresses = 'localhost'"
    $conf | Set-Content -Path $PgConf -Encoding ascii
    Restart-Service $PgServiceName
    Write-Host "PostgreSQL now listens on localhost only."
}
Set-Service $PgServiceName -StartupType Automatic
Start-Service $PgServiceName

$env:PGPASSWORD = $SuperPassword
$psql = Join-Path $PgBin "psql.exe"
function Invoke-Psql([string]$Sql) {
    $out = & $psql -h localhost -U postgres -d postgres -v ON_ERROR_STOP=1 -tAc $Sql
    if ($LASTEXITCODE -ne 0) { throw "psql failed: $Sql" }
    return $out
}

if ((Invoke-Psql "SELECT 1 FROM pg_roles WHERE rolname = 'choresome'") -ne "1") {
    Invoke-Psql "CREATE ROLE choresome LOGIN PASSWORD '$AppPassword'" | Out-Null
    Write-Host "Created database role 'choresome'."
} else {
    Invoke-Psql "ALTER ROLE choresome WITH LOGIN PASSWORD '$AppPassword'" | Out-Null
}
if ((Invoke-Psql "SELECT 1 FROM pg_database WHERE datname = 'choresome'") -ne "1") {
    Invoke-Psql "CREATE DATABASE choresome OWNER choresome" | Out-Null
    Write-Host "Created database 'choresome'."
}
Remove-Item Env:\PGPASSWORD

# -----------------------------
# 2. App configuration
# -----------------------------

if (-not (Test-Path $EnvFile)) {
    @(
        "# Hosted Choresome configuration (see .env.example). Generated by setup-hosted.ps1; keep private.",
        "DATABASE_URL=`"postgresql://choresome:$AppPassword@localhost:5432/choresome?schema=public`"",
        "# Change to the public https URL once the domain + Cloudflare Tunnel are live, then restart the task.",
        "APP_URL=`"http://localhost:$Port`"",
        "PORT=$Port",
        "# Only localhost (i.e. cloudflared) can reach this port, so its forwarded client IPs can be trusted.",
        "TRUST_PROXY=true",
        "SIGNUPS_ENABLED=true",
        "BACKUP_DIR=`"$AppDirectory\backups`"",
        "PG_DUMP_PATH=`"$PgBin\pg_dump.exe`"",
        "BACKUP_INTERVAL_HOURS=24",
        "BACKUP_RETENTION=14"
    ) | Set-Content -Path $EnvFile -Encoding ascii
    Write-Host "Wrote $EnvFile."
} else {
    Write-Host "$EnvFile already exists; leaving it as is."
}
Protect-File $EnvFile

# -----------------------------
# 3. Startup task
# -----------------------------

$action = New-ScheduledTaskAction -Execute "cmd.exe" -Argument "/c `"$AppDirectory\scripts\server\hosted\start-hosted.cmd`""
$trigger = New-ScheduledTaskTrigger -AtStartup
# ExecutionTimeLimit defaults to 72 hours, after which Task Scheduler kills
# the task -- fatal for a long-running server. Zero means "no limit".
$settings = New-ScheduledTaskSettingsSet `
    -StartWhenAvailable `
    -ExecutionTimeLimit ([TimeSpan]::Zero) `
    -RestartCount 10 `
    -RestartInterval (New-TimeSpan -Minutes 1)

Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $trigger -Settings $settings -RunLevel Highest -Force | Out-Null
Write-Host "Registered the '$TaskName' startup task."

Write-Host "Setup complete. Run scripts\server\hosted\deploy-hosted.ps1 to build and start it." -ForegroundColor Green
